### PR TITLE
Adds setAppVersion

### PR DESCRIPTION
**Pull request by sidferreira**

### CODE REVIEW

**Comment by sidferreira** [comment]
May need some linting...
Maybe add prettier?

**Comment by sidferreira** [comment]
Is there any scheduled release?

**Comment by e7mac** [comment]
the beta is out with just this PR added (1.0.12-beta1)
Pending QA, the final release will be sometime next week

**Comment by e7mac** [comment]
sorry for the delay, but please find the release 1.0.13 and let us know if you have any trouble with it

**Pull request merged**
